"""Catalog of the 21 bugs (ids 10-30) added on top of the original hand-written
bugs 1-9, used by generate_demo_bugs.py to produce mini_repo/*.py, demo/bug_reports/,
and demo/logs/ consistently. Keeping this as data (not 21 hand-written file pairs)
makes the set easy to audit, extend, or regenerate.

Each entry's `category` records *why* it was designed the way it was, mirroring the
categories established in demo/README.md:
  - "fallback": at least one of the fixed 6 probe values ([], None, 0, "", {}, -1,
    repeated across every parameter) reproduces the bug on its own.
  - "llm_dict_key": needs a real, correctly-typed dict + a specific missing string
    key -- two coordinated, differently-typed arguments the fallback can't produce.
  - "llm_threshold": needs a number past a threshold well outside the 6 fixed values.
  - "llm_relational": needs two coordinated numbers satisfying a > comparison that
    no repeated single value can satisfy.
  - "llm_wraparound": needs an int outside a list's valid range, accounting for
    Python's negative-index wraparound (so -1 alone doesn't trigger it).
  - "llm_string_length": needs a string longer than a threshold (empty string is
    always too short, so it can't accidentally match).
"""

from __future__ import annotations

BUGS = [
    # --- fallback-coverable (category: "fallback") ---
    {
        "id": 10,
        "slug": "accounts_missing_email",
        "category": "fallback",
        "module": "accounts",
        "function": "get_account_email",
        "source": 'def get_account_email(account: dict) -> str:\n    # Intentional bug: crashes when account is an empty/unknown record instead\n    # of returning a placeholder.\n    return account["email"]\n',
        "crash_statement": 'return account["email"]',
        "error_type": "KeyError",
        "error_message": "'email'",
        "title": "Account email lookup crashes for records missing an email field",
        "description": "When the account service looks up a display email for a legacy record with no email field, it throws a runtime exception and returns HTTP 500 instead of a placeholder.",
        "expected": "The endpoint should return a placeholder (e.g. \"no email on file\") when the field is missing.",
        "actual": "The endpoint throws an exception and fails the request.",
        "hint": "Trigger `/accounts/lookup-email` for a legacy account record with no `email` field.",
        "endpoint": "/accounts/lookup-email",
        "warn_detail": "account={}",
        "caller_func": "handle_account_email_request",
    },
    {
        "id": 11,
        "slug": "tagging_no_tags",
        "category": "fallback",
        "module": "tagging",
        "function": "first_tag",
        "source": "def first_tag(tags: list[str]) -> str:\n    # Intentional bug: crashes when a post has no tags instead of returning\n    # a default category.\n    return tags[0]\n",
        "crash_statement": "return tags[0]",
        "error_type": "IndexError",
        "error_message": "list index out of range",
        "title": "Post categorization crashes for untagged posts",
        "description": "When the content service tries to derive a primary category from a post's first tag, it throws a runtime exception for posts with zero tags instead of using a default category.",
        "expected": "The endpoint should fall back to a default category (e.g. \"uncategorized\") when there are no tags.",
        "actual": "The endpoint throws an exception and fails the request.",
        "hint": "Trigger `/posts/categorize` for a post with an empty `tags` list.",
        "endpoint": "/posts/categorize",
        "warn_detail": "tags=[]",
        "caller_func": "handle_post_categorize_request",
    },
    {
        "id": 12,
        "slug": "telemetry_zero_hours",
        "category": "fallback",
        "module": "telemetry",
        "function": "compute_average_speed",
        "source": "def compute_average_speed(distance_km: float, hours: float) -> float:\n    # Intentional bug: crashes when hours is zero (e.g. a GPS glitch reporting\n    # an instantaneous reading) instead of returning 0.\n    return distance_km / hours\n",
        "crash_statement": "return distance_km / hours",
        "error_type": "ZeroDivisionError",
        "error_message": "float division by zero",
        "title": "Trip telemetry crashes on zero-duration GPS readings",
        "description": "When a GPS device reports a trip segment with zero elapsed hours (a known device glitch), the telemetry service throws a runtime exception instead of skipping the segment.",
        "expected": "The service should return 0 average speed for a zero-duration segment, not crash.",
        "actual": "The service throws an exception and the telemetry batch job fails.",
        "hint": "Trigger the telemetry batch job with a trip segment where `hours=0`.",
        "endpoint": "/jobs/telemetry_batch",
        "warn_detail": "distance_km=12.4 hours=0",
        "caller_func": "run_telemetry_batch_job",
    },
    {
        "id": 13,
        "slug": "textutils_empty_word",
        "category": "fallback",
        "module": "textutils",
        "function": "uppercase_first_letter",
        "source": "def uppercase_first_letter(word: str) -> str:\n    # Intentional bug: crashes on an empty string instead of returning it\n    # unchanged.\n    return word[0].upper() + word[1:]\n",
        "crash_statement": "return word[0].upper() + word[1:]",
        "error_type": "IndexError",
        "error_message": "string index out of range",
        "title": "Title-casing helper crashes on empty product names",
        "description": "When the catalog import job title-cases a product name and encounters an empty name field (a known data-entry error), it throws a runtime exception instead of skipping the field.",
        "expected": "The job should skip title-casing for an empty name instead of crashing.",
        "actual": "The job throws an exception and the import batch fails.",
        "hint": "Trigger the catalog import job with a product record where `name=\"\"`.",
        "endpoint": "/jobs/catalog_import",
        "warn_detail": "name=",
        "caller_func": "run_catalog_import_job",
    },
    {
        "id": 14,
        "slug": "parsing_none_percentage",
        "category": "fallback",
        "module": "parsing",
        "function": "parse_percentage",
        "source": "def parse_percentage(value: str) -> float:\n    # Intentional bug: crashes when value is None (field omitted upstream)\n    # instead of returning 0.0.\n    return float(value.strip(\"%\")) / 100\n",
        "crash_statement": 'return float(value.strip("%")) / 100',
        "error_type": "AttributeError",
        "error_message": "'NoneType' object has no attribute 'strip'",
        "title": "Discount import crashes when percentage field is omitted",
        "description": "When the promotions feed omits the discount percentage field for a record (sent as null), the import job throws a runtime exception instead of treating it as 0%.",
        "expected": "The job should treat a missing percentage as 0% instead of crashing.",
        "actual": "The job throws an exception and the import batch fails.",
        "hint": "Trigger the promotions import job with a record where `percentage=null`.",
        "endpoint": "/jobs/promotions_import",
        "warn_detail": "percentage=null",
        "caller_func": "run_promotions_import_job",
    },
    {
        "id": 15,
        "slug": "cart_none_items",
        "category": "fallback",
        "module": "cart",
        "function": "total_cart_value",
        "source": "def total_cart_value(items: list[dict]) -> float:\n    # Intentional bug: crashes when items is None (session expired mid-checkout)\n    # instead of treating it as an empty cart.\n    return sum(item[\"price\"] for item in items)\n",
        "crash_statement": 'return sum(item["price"] for item in items)',
        "error_type": "TypeError",
        "error_message": "'NoneType' object is not iterable",
        "title": "Checkout total crashes for expired cart sessions",
        "description": "When a checkout request arrives for a session whose cart expired server-side (items resolves to null), the checkout service throws a runtime exception instead of treating it as an empty cart.",
        "expected": "The endpoint should treat a null cart as empty (total $0) instead of crashing.",
        "actual": "The endpoint throws an exception and checkout fails.",
        "hint": "Trigger `/checkout/total` for a session whose cart items resolve to null.",
        "endpoint": "/checkout/total",
        "warn_detail": "items=null",
        "caller_func": "handle_checkout_total_request",
    },
    {
        "id": 16,
        "slug": "orders_no_history",
        "category": "fallback",
        "module": "orders",
        "function": "most_recent_order",
        "source": 'def most_recent_order(orders: list[dict]) -> dict:\n    # Intentional bug: crashes for a customer with no order history instead\n    # of returning None.\n    return max(orders, key=lambda o: o["date"])\n',
        "crash_statement": 'return max(orders, key=lambda o: o["date"])',
        "error_type": "ValueError",
        "error_message": "max() arg is an empty sequence",
        "title": "Recommendations service crashes for first-time customers",
        "description": "When the recommendations service tries to find a new customer's most recent order to personalize suggestions, it throws a runtime exception for customers with zero order history.",
        "expected": "The service should return no personalization (not crash) for a customer with no orders.",
        "actual": "The service throws an exception and the recommendations widget fails to load.",
        "hint": "Trigger `/recommendations/personalize` for a customer with an empty `orders` list.",
        "endpoint": "/recommendations/personalize",
        "warn_detail": "orders=[]",
        "caller_func": "handle_recommendations_request",
    },
    {
        "id": 17,
        "slug": "finance_zero_shareholders",
        "category": "fallback",
        "module": "finance",
        "function": "divide_shares",
        "source": "def divide_shares(total: float, shareholders: int) -> float:\n    # Intentional bug: crashes when shareholders is zero (a data-migration\n    # edge case) instead of returning 0.\n    return total / shareholders\n",
        "crash_statement": "return total / shareholders",
        "error_type": "ZeroDivisionError",
        "error_message": "division by zero",
        "title": "Dividend calculator crashes for entities with zero shareholders",
        "description": "When the dividend batch job processes an entity mid-migration with zero shareholders on record, it throws a runtime exception instead of skipping the entity.",
        "expected": "The job should skip an entity with zero shareholders, not crash the whole batch.",
        "actual": "The job throws an exception and the dividend batch fails.",
        "hint": "Trigger the dividend batch job for an entity with `shareholders=0`.",
        "endpoint": "/jobs/dividend_batch",
        "warn_detail": "total=50000 shareholders=0",
        "caller_func": "run_dividend_batch_job",
    },
    # --- llm_dict_key ---
    {
        "id": 18,
        "slug": "roles_missing_permission",
        "category": "llm_dict_key",
        "module": "roles",
        "function": "get_user_permission",
        "source": 'def get_user_permission(permissions: dict[str, list[str]], role: str) -> list[str]:\n    # Intentional bug: crashes with KeyError for a role not in the permission\n    # map instead of denying access cleanly.\n    return permissions[role]\n',
        "crash_statement": "return permissions[role]",
        "error_type": "KeyError",
        "error_message": "'viewer'",
        "title": "Access control crashes for a role not in the permission map",
        "description": "When a request comes in for a role that isn't yet registered in the permission map (e.g. a newly introduced 'viewer' role), the access-control service throws a runtime exception instead of denying access.",
        "expected": "The endpoint should deny access cleanly (403) for an unrecognized role, not crash.",
        "actual": "The endpoint throws an exception and returns HTTP 500.",
        "hint": "Trigger `/access/check` for role `\"viewer\"`, which isn't yet in the permission map (`{\"admin\": [...], \"editor\": [...]}`).",
        "endpoint": "/access/check",
        "warn_detail": "role=viewer",
        "caller_func": "handle_access_check_request",
    },
    {
        "id": 19,
        "slug": "i18n_missing_locale",
        "category": "llm_dict_key",
        "module": "i18n",
        "function": "get_translation",
        "source": 'def get_translation(translations: dict[str, str], locale: str) -> str:\n    # Intentional bug: crashes with KeyError for an unsupported locale instead\n    # of falling back to English.\n    return translations[locale]\n',
        "crash_statement": "return translations[locale]",
        "error_type": "KeyError",
        "error_message": "'de'",
        "title": "Translation lookup crashes for an unsupported locale",
        "description": "When a request specifies a locale that hasn't been translated yet (e.g. `\"de\"`), the i18n service throws a runtime exception instead of falling back to English.",
        "expected": "The endpoint should fall back to English for an unsupported locale, not crash.",
        "actual": "The endpoint throws an exception and returns HTTP 500.",
        "hint": "Trigger `/i18n/translate` with `locale=\"de\"` against a translation map containing only `{\"en\": ..., \"fr\": ...}`.",
        "endpoint": "/i18n/translate",
        "warn_detail": "locale=de",
        "caller_func": "handle_translate_request",
    },
    {
        "id": 20,
        "slug": "featureflags_unknown_flag",
        "category": "llm_dict_key",
        "module": "featureflags",
        "function": "get_feature_flag",
        "source": "def get_feature_flag(flags: dict[str, bool], flag_name: str) -> bool:\n    # Intentional bug: crashes with KeyError for a flag name that was never\n    # registered instead of defaulting to off.\n    return flags[flag_name]\n",
        "crash_statement": "return flags[flag_name]",
        "error_type": "KeyError",
        "error_message": "'beta_search'",
        "title": "Feature flag lookup crashes for an unregistered flag",
        "description": "When client code checks a feature flag that was referenced before it was registered server-side (e.g. `\"beta_search\"`), the flag service throws a runtime exception instead of defaulting to off.",
        "expected": "The endpoint should default to `false` for an unregistered flag, not crash.",
        "actual": "The endpoint throws an exception and returns HTTP 500.",
        "hint": "Trigger `/flags/check` with `flag_name=\"beta_search\"` against a flag map containing only `{\"dark_mode\": true}`.",
        "endpoint": "/flags/check",
        "warn_detail": "flag_name=beta_search",
        "caller_func": "handle_flag_check_request",
    },
    # --- llm_threshold ---
    {
        "id": 21,
        "slug": "hvac_overlimit_fan_speed",
        "category": "llm_threshold",
        "module": "hvac",
        "function": "set_fan_speed",
        "source": 'def set_fan_speed(percent: int) -> str:\n    # Intentional bug: raises a bare, unhandled ValueError above 100% instead\n    # of rejecting the request cleanly.\n    if percent > 100:\n        raise ValueError(f"Fan speed {percent}% exceeds maximum of 100%")\n    return f"Fan set to {percent}%"\n',
        "crash_statement": 'raise ValueError(f"Fan speed {percent}% exceeds maximum of 100%")',
        "error_type": "ValueError",
        "error_message": "Fan speed 140% exceeds maximum of 100%",
        "title": "HVAC control crashes on over-limit fan speed request",
        "description": "When a technician sends a fan speed setpoint above 100%, the HVAC control service throws a runtime exception and returns HTTP 500 instead of rejecting it cleanly.",
        "expected": "The endpoint should return a 400 response for an out-of-range fan speed, not crash.",
        "actual": "The endpoint throws an exception and the control request fails ungracefully.",
        "hint": "Trigger `/hvac/fan/set` with `{\"percent\": 140}`, above the 100% maximum.",
        "endpoint": "/hvac/fan/set",
        "warn_detail": "percent=140",
        "caller_func": "handle_fan_set_request",
    },
    {
        "id": 22,
        "slug": "billing2_excessive_overdue",
        "category": "llm_threshold",
        "module": "billing2",
        "function": "apply_late_fee_days",
        "source": 'def apply_late_fee_days(days_overdue: int) -> float:\n    # Intentional bug: raises a bare, unhandled ValueError past the collections\n    # threshold instead of routing to a collections workflow.\n    if days_overdue > 90:\n        raise ValueError("account overdue beyond 90 days, must route to collections")\n    return days_overdue * 1.5\n',
        "crash_statement": 'raise ValueError("account overdue beyond 90 days, must route to collections")',
        "error_type": "ValueError",
        "error_message": "account overdue beyond 90 days, must route to collections",
        "title": "Late fee job crashes on severely overdue accounts",
        "description": "When the late-fee batch job processes an account overdue by more than 90 days, it throws a runtime exception instead of routing it to the collections workflow.",
        "expected": "The job should route accounts overdue beyond 90 days to collections, not crash.",
        "actual": "The job throws an exception and the whole late-fee batch fails.",
        "hint": "Trigger the late-fee batch job for an account with `days_overdue=120`.",
        "endpoint": "/jobs/late_fee_batch",
        "warn_detail": "days_overdue=120",
        "caller_func": "run_late_fee_batch_job",
    },
    {
        "id": 23,
        "slug": "retrypolicy_excessive_retries",
        "category": "llm_threshold",
        "module": "retrypolicy",
        "function": "set_max_retries",
        "source": 'def set_max_retries(n: int) -> str:\n    # Intentional bug: raises a bare, unhandled ValueError for an unreasonable\n    # retry count instead of rejecting the config change cleanly.\n    if n > 10:\n        raise ValueError(f"retry count {n} is unreasonably high")\n    return f"max retries set to {n}"\n',
        "crash_statement": 'raise ValueError(f"retry count {n} is unreasonably high")',
        "error_type": "ValueError",
        "error_message": "retry count 50 is unreasonably high",
        "title": "Retry policy config crashes on an unreasonable retry count",
        "description": "When an operator submits a retry-policy config change with an unreasonably high retry count, the config service throws a runtime exception instead of rejecting the change.",
        "expected": "The endpoint should return a 400 response for an unreasonable retry count, not crash.",
        "actual": "The endpoint throws an exception and the config change fails ungracefully.",
        "hint": "Trigger `/config/retry-policy` with `{\"n\": 50}`, well above the sane maximum of 10.",
        "endpoint": "/config/retry-policy",
        "warn_detail": "n=50",
        "caller_func": "handle_retry_policy_request",
    },
    # --- llm_relational ---
    {
        "id": 24,
        "slug": "booking_overbooked_seats",
        "category": "llm_relational",
        "module": "booking",
        "function": "book_seats",
        "source": 'def book_seats(available_seats: int, requested_seats: int) -> int:\n    # Intentional bug: raises a bare, unhandled ValueError when overbooked\n    # instead of returning a waitlist response.\n    if requested_seats > available_seats:\n        raise ValueError("not enough seats available")\n    return available_seats - requested_seats\n',
        "crash_statement": 'raise ValueError("not enough seats available")',
        "error_type": "ValueError",
        "error_message": "not enough seats available",
        "title": "Seat booking crashes when requested seats exceed availability",
        "description": "When a group booking requests more seats than are available on a flight, the booking service throws a runtime exception instead of offering a waitlist.",
        "expected": "The endpoint should offer a waitlist response when overbooked, not crash.",
        "actual": "The endpoint throws an exception and the booking request fails ungracefully.",
        "hint": "Trigger `/booking/reserve` for a flight with `available_seats=5` and a request for `requested_seats=12`.",
        "endpoint": "/booking/reserve",
        "warn_detail": "available_seats=5 requested_seats=12",
        "caller_func": "handle_booking_reserve_request",
    },
    {
        "id": 25,
        "slug": "banking_overdraft_transfer",
        "category": "llm_relational",
        "module": "banking",
        "function": "transfer_funds",
        "source": 'def transfer_funds(source_balance: float, transfer_amount: float) -> float:\n    # Intentional bug: raises a bare, unhandled ValueError when the transfer\n    # exceeds the balance instead of a clean decline response.\n    if transfer_amount > source_balance:\n        raise ValueError("insufficient balance for transfer")\n    return source_balance - transfer_amount\n',
        "crash_statement": 'raise ValueError("insufficient balance for transfer")',
        "error_type": "ValueError",
        "error_message": "insufficient balance for transfer",
        "title": "Funds transfer crashes when amount exceeds source balance",
        "description": "When a customer requests a transfer larger than their source account balance, the transfer service throws a runtime exception instead of a clean decline.",
        "expected": "The endpoint should return a 402 decline response, not crash.",
        "actual": "The endpoint throws an exception and the transfer request fails ungracefully.",
        "hint": "Trigger `/banking/transfer` for an account with `source_balance=200` requesting `transfer_amount=500`.",
        "endpoint": "/banking/transfer",
        "warn_detail": "source_balance=200 transfer_amount=500",
        "caller_func": "handle_transfer_request",
    },
    {
        "id": 26,
        "slug": "logistics_backorder_needed",
        "category": "llm_relational",
        "module": "logistics",
        "function": "schedule_delivery",
        "source": 'def schedule_delivery(current_stock: int, order_quantity: int) -> str:\n    # Intentional bug: raises a bare, unhandled ValueError when stock is\n    # insufficient instead of triggering a backorder workflow.\n    if order_quantity > current_stock:\n        raise ValueError("insufficient stock, backorder required")\n    return "shipped"\n',
        "crash_statement": 'raise ValueError("insufficient stock, backorder required")',
        "error_type": "ValueError",
        "error_message": "insufficient stock, backorder required",
        "title": "Delivery scheduling crashes when order exceeds current stock",
        "description": "When an order quantity exceeds the current warehouse stock, the delivery-scheduling service throws a runtime exception instead of triggering a backorder workflow.",
        "expected": "The endpoint should trigger a backorder workflow when stock is insufficient, not crash.",
        "actual": "The endpoint throws an exception and the delivery scheduling request fails ungracefully.",
        "hint": "Trigger `/logistics/schedule` for a warehouse with `current_stock=8` and an `order_quantity=25`.",
        "endpoint": "/logistics/schedule",
        "warn_detail": "current_stock=8 order_quantity=25",
        "caller_func": "handle_schedule_delivery_request",
    },
    # --- llm_wraparound ---
    {
        "id": 27,
        "slug": "calendarutils_invalid_month",
        "category": "llm_wraparound",
        "module": "calendarutils",
        "function": "get_month_name",
        "source": '_MONTH_NAMES = [\n    "Jan", "Feb", "Mar", "Apr", "May", "Jun",\n    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",\n]\n\n\ndef get_month_name(month_index: int) -> str:\n    # Intentional bug: crashes with IndexError for an out-of-range month index\n    # instead of raising a clear validation error.\n    return _MONTH_NAMES[month_index]\n',
        "crash_statement": "return _MONTH_NAMES[month_index]",
        "error_type": "IndexError",
        "error_message": "list index out of range",
        "title": "Calendar sync crashes on out-of-range month index",
        "description": "When the third-party calendar API sends a month index outside the valid 0-11 range (a known off-by-one bug in their integration), the calendar sync service throws a runtime exception instead of skipping the malformed entry.",
        "expected": "The service should skip / reject an out-of-range month index with a clear validation error, not crash.",
        "actual": "The service throws an exception and the whole sync batch fails.",
        "hint": "Trigger the calendar sync job with a month index of 14 (outside the valid 0-11 range).",
        "endpoint": "/jobs/calendar_month_sync",
        "warn_detail": "month_index=14",
        "caller_func": "run_calendar_month_sync_job",
    },
    {
        "id": 28,
        "slug": "tickets_invalid_priority",
        "category": "llm_wraparound",
        "module": "tickets",
        "function": "get_priority_label",
        "source": '_PRIORITY_LEVELS = ["low", "medium", "high", "critical"]\n\n\ndef get_priority_label(level: int) -> str:\n    # Intentional bug: crashes with IndexError for a priority level outside\n    # the valid 0-3 range instead of defaulting to "low".\n    return _PRIORITY_LEVELS[level]\n',
        "crash_statement": "return _PRIORITY_LEVELS[level]",
        "error_type": "IndexError",
        "error_message": "list index out of range",
        "title": "Ticket triage crashes on out-of-range priority level",
        "description": "When an upstream integration sends a priority level outside the valid 0-3 range (a known bug in a partner's webhook payload), the ticket triage service throws a runtime exception instead of defaulting to low priority.",
        "expected": "The service should default to \"low\" priority for an out-of-range value, not crash.",
        "actual": "The service throws an exception and the ticket fails to import.",
        "hint": "Trigger the ticket import webhook with `level=7` (outside the valid 0-3 range).",
        "endpoint": "/webhooks/ticket_import",
        "warn_detail": "level=7",
        "caller_func": "handle_ticket_import_webhook",
    },
    # --- llm_string_length ---
    {
        "id": 29,
        "slug": "users_username_too_long",
        "category": "llm_string_length",
        "module": "userauth",
        "function": "validate_username",
        "source": 'def validate_username(username: str) -> str:\n    # Intentional bug: raises a bare, unhandled ValueError for an overlong\n    # username instead of rejecting the signup request cleanly.\n    if len(username) > 20:\n        raise ValueError("username exceeds maximum length of 20")\n    return username\n',
        "crash_statement": 'raise ValueError("username exceeds maximum length of 20")',
        "error_type": "ValueError",
        "error_message": "username exceeds maximum length of 20",
        "title": "Signup crashes on an overlong username",
        "description": "When a signup request includes a username longer than 20 characters, the signup service throws a runtime exception instead of rejecting the request cleanly.",
        "expected": "The endpoint should return a 400 response for an overlong username, not crash.",
        "actual": "The endpoint throws an exception and the signup request fails ungracefully.",
        "hint": "Trigger `/signup` with a username longer than 20 characters (e.g. copy-pasted from a display name field).",
        "endpoint": "/signup",
        "warn_detail": "username=this_username_is_way_too_long_for_the_system",
        "caller_func": "handle_signup_request",
    },
    {
        "id": 30,
        "slug": "catalog_sku_too_long",
        "category": "llm_string_length",
        "module": "catalog",
        "function": "validate_product_sku",
        "source": 'def validate_product_sku(sku: str) -> str:\n    # Intentional bug: raises a bare, unhandled ValueError for an overlong SKU\n    # instead of rejecting the catalog entry cleanly.\n    if len(sku) > 12:\n        raise ValueError("sku exceeds maximum length of 12")\n    return sku\n',
        "crash_statement": 'raise ValueError("sku exceeds maximum length of 12")',
        "error_type": "ValueError",
        "error_message": "sku exceeds maximum length of 12",
        "title": "Catalog import crashes on an overlong SKU",
        "description": "When the supplier catalog feed includes a SKU longer than 12 characters (a known formatting issue from one supplier), the catalog import job throws a runtime exception instead of rejecting that record.",
        "expected": "The job should reject an overlong SKU with a clear validation error, not crash the whole batch.",
        "actual": "The job throws an exception and the catalog import batch fails.",
        "hint": "Trigger the catalog import job with a SKU longer than 12 characters (e.g. `\"SUPPLIER-SKU-000123456\"`).",
        "endpoint": "/jobs/catalog_sku_import",
        "warn_detail": "sku=SUPPLIER-SKU-000123456",
        "caller_func": "run_catalog_sku_import_job",
    },
]
